export const ACTION_TYPE = {
	AUTHORIZE: "AUTHORIZE",
	LOGOUT: "LOGOUT",
	SET_USER: "SET_USER",
	SET_ACCOUNTS_DATA: "SET_ACCOUNTS_DATA",
	SHOW_ALERT_MESSAGE: "SHOW_ALERT_MESSAGE",
	HIDE_ALERT_MESSAGE: "HIDE_ALERT_MESSAGE",
	SET_ALERT_MESSAGE: "SET_ALERT_MESSAGE",
	SET_ACCOUNT_TYPES_DATA: "SET_ACCOUNT_TYPES_DATA",
	SET_OPERATION_CATEGORIES_DATA: "SET_OPERATION_CATEGORIES_DATA",
	SET_AUTH_CHECKED: "SET_AUTH_CHECKED",
};
